
import { Part_one } from '../../components/molecules/header/header'
import { Menu_initial } from '../../components/molecules/menu/menu'
import { My } from '../../components/molecules/my/my'


import './globals.css'
import { Inter } from 'next/font/google'
import { Lenguaje } from '../../components/molecules/lenguajes/lenguaje'
import { Repositore } from '../../components/molecules/repostirores/repositores'
import { Study } from '../../components/molecules/estudios/estudios'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Porfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} >
       
        <Menu_initial/>
        <Part_one/>  
         <My/>  
        <Lenguaje/> 
        <Repositore/>
         <Study/>
        {children}
      </body>
    </html>
  )
}